# Generated by Django 5.1 on 2024-08-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_remove_contact_is_blacklisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ct_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='ct_gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
