# Generated by Django 5.1 on 2024-08-31 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_ct_email_contact_ct_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='ct_email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='ct_gender',
        ),
    ]
