# Generated by Django 5.1 on 2024-08-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_remove_contact_ct_email_remove_contact_ct_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
