# Generated by Django 5.1 on 2024-08-31 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('O', '其他')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ct_phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^\\d{11}$', '请输入11位手机号码。')]),
        ),
    ]
