# Generated by Django 5.1 on 2024-08-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_birthday_contact_email_contact_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='contact_avatars/'),
        ),
    ]
